### ISSUE TITLE
大佬你好，可以请教你openvino部署相关的问题吗？

### ISSUE THREAD

**Issue by szu-lisili** [thb1314/thb1314.github.io#2]
大佬，我看了你的博客关于MQBench中openvino部署相关的文章，收益很大。我自己想尝试一边QAT量化并且部署，我是先用自定义的伪量化模块去训练模型（简单的分割模型），然后转成onnx之后再把相应参数转成openvino的FakeQuantize，再使用mo生成xml文件，但是跟pytorch的推理精度完全对不上，可以请教一下可能会出错的地方吗？可以要您的联系方式吗，有偿也行 /(ㄒoㄒ)/~~

**Comment by thb1314** [comment]
> 大佬，我看了你的博客关于MQBench中openvino部署相关的文章，收益很大。我自己想尝试一边QAT量化并且部署，我是先用自定义的伪量化模块去训练模型（简单的分割模型），然后转成onnx之后再把相应参数转成openvino的FakeQuantize，再使用mo生成xml文件，但是跟pytorch的推理精度完全对不上，可以请教一下可能会出错的地方吗？可以要您的联系方式吗，有偿也行 /(ㄒoㄒ)/~~

@szu-lisili wechat发到haibintian@foxmail.com 准备好钱（狗头）

**Comment by szu-lisili** [comment]
> 
佬，已经给你发了，注意查收噢

**Comment by szu-lisili** [comment]
> > 大佬，我看了你的博客关于MQBench中openvino部署相关的文章，收益很大。我自己想尝试一边QAT量化并且部署，我是先用自定义的伪量化模块去训练模型（简单的分割模型），然后转成onnx之后再把相应参数转成openvino的FakeQuantize，再使用mo生成xml文件，但是跟pytorch的推理精度完全对不上，可以请教一下可能会出错的地方吗？可以要您的联系方式吗，有偿也行 /(ㄒoㄒ)/~~
> 
> @szu-lisili wechat发到[haibintian@foxmail.com](mailto:haibintian@foxmail.com) 准备好钱（狗头）

大佬，微信号是13229734303，已经发你邮箱了，你有收到吗/(ㄒoㄒ)/~~。。。
